#
# OpenBSD Vagrant box
#

# shared folder
MY_VM_CODE = "./vmcode/"
CODE_MNT = "/opt/vmcode"
CODE_MNT_OPT = ["dmode=775,fmode=644"]

# Serial console log path on the host (set VAGRANT_SERIAL_LOG env var to override)
SERIAL_LOG = ENV.fetch("VAGRANT_SERIAL_LOG", "/tmp/openbsd-serial.log")

Vagrant.configure("2") do |config|

    config.vm.box = "OpenBSD.box"
    config.vm.box_check_update = false
    config.ssh.username = "bsduser"
    config.ssh.insert_key = true
    config.ssh.forward_agent = false
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # VirtualBox: enable COM1 serial port for console capture
    config.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vbox.customize ["modifyvm", :id, "--uartmode1", "file", SERIAL_LOG]
    end

    # Libvirt: enable serial console to file
    config.vm.provider :libvirt do |libv|
        libv.serial :type => "file", :source => {:path => SERIAL_LOG}
    end

    # Virtual machines
    config.vm.define "openbsd" do |mainvm|
        config.vm.hostname = "openbsd"
        config.vm.synced_folder MY_VM_CODE, CODE_MNT, type: "rsync",
            mount_options: CODE_MNT_OPT,
            rsync__rsync_path: "doas rsync"
    end

    config.vm.provision :shell,
        :privileged => true, 
        :path => "vagrant.sh",
        :binary => true, 
        name: "vagrant sh"

end

# -*- mode: ruby -*-
# vi: ft=ruby :